// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcv5ZF4MwSDUPMwuNcM3iyhbnsD_f_8_E',
    appId: '1:87338545408:web:af58eb7f8666c7f6fe43e5',
    messagingSenderId: '87338545408',
    projectId: 'intervue-my',
    authDomain: 'intervue-my.firebaseapp.com',
    storageBucket: 'intervue-my.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1frUGOO8CQZbVQSHQlh80TuBNNpVFv2I',
    appId: '1:87338545408:android:db19447b8a6cb809fe43e5',
    messagingSenderId: '87338545408',
    projectId: 'intervue-my',
    storageBucket: 'intervue-my.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE7TF2SYtiTRvofs9-ncphe1FfU34l8Qs',
    appId: '1:87338545408:ios:a8e5087889eab000fe43e5',
    messagingSenderId: '87338545408',
    projectId: 'intervue-my',
    storageBucket: 'intervue-my.appspot.com',
    iosBundleId: 'com.example.talentsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE7TF2SYtiTRvofs9-ncphe1FfU34l8Qs',
    appId: '1:87338545408:ios:ebaf4b61f4e25358fe43e5',
    messagingSenderId: '87338545408',
    projectId: 'intervue-my',
    storageBucket: 'intervue-my.appspot.com',
    iosBundleId: 'com.example.talentsync.RunnerTests',
  );
}
